---
# tasks file for dns
  - name: install packages
    yum:
      state: present
      name:
        - bind
        - bind-utils
        # - ntp

  - name: start chronyd
    service:
      name: chronyd
      state: restarted
      enabled: true

