---
# tasks file for dns
  - name: install packages
    yum:
      state: present
      name:
        - bind
        - bind-utils
        # - ntp

  - name: start chronyd
    service:
      name: chronyd
      state: restarted
      enabled: true

  # - name: stop and disable chronyd
  #   service:
  #       name: chronyd
  #       state: stopped
  #       enabled: false
  # - name: start and enable ntpd
  #   service:
  #     name: ntpd
  #     state: started
  #     enabled: true

  - name: copy resolv.conf to the servers
    template:
      src: roles/dns/files/resolv.conf.j2
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: 0644

  - name: Copy named.conf to servers
    template:
       src: roles/dns/files/named.conf.j2
       dest: /etc/openvpn/named.conf
      #  owner: frr
      #  group: frr
      #  mode: 0640
  - name: Copy dns.lab to ns01
    template:
       src: roles/dns/files/named.dns.lab.j2
       dest: /etc/openvpn/named.dns.lab
      #  owner: frr
      #  group: frr
      #  mode: 0640

  - name: ensure named is running and enabled
    service:
      name: named
      state: restarted
      enabled: yes

