---
# tasks file for dns
  - name: install packages
    yum:
      state: present
      name:
        - bind
        - bind-utils
        # - ntp

  - name: start chronyd
    service:
      name: chronyd
      state: restarted
      enabled: true

  - name: started named
    service:
      name: named
      state: started
      enabled: yes

  - name: copy resolv.conf to the servers
    template:
      src: resolv.conf.j2
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: 0644

  - name: Copy named.conf to servers
    template:
       src: named.conf.j2
       dest: /etc/openvpn/named.conf
       owner: root
       group: root
       mode: 0644
  - name: Copy dns.lab to ns01
    template:
       src: named.dns.lab.j2
       dest: /etc/openvpn/named.dns.lab
       owner: root
       group: root
       mode: 0644

  - name: ensure named is running and enabled
    service:
      name: named
      state: restarted
      enabled: yes

